# Generated by Django 4.1 on 2022-09-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='review',
            field=models.CharField(max_length=150),
        ),
    ]
